### ISSUE TITLE
the CommandItemCount can`t load 

### ISSUE THREAD

**Issue by charlesli524** [Vl4dimyr/CommandItemCount#1]
The situation is that when I turned on risk of rain 2, bepinex did not successfully load the CommandItemCount mod, as if it was not installed at all.

**Comment by Vl4dimyr** [comment]
Hey which version do you use? I made a mistake in 1.0.0 and 1.0.1, so they are not working at all ... if you are using 1.0.2 or 1.0.3 the mod should load, if not please provide more information on how you installed the mod.

**Comment by charlesli524** [comment]
I just put CommandItemCount.dll into BepinEx/plugins normally, but when I start the game, BepinEx does not show that it is running CommandItemCount.dll

**Comment by charlesli524** [comment]
i am also installed 1.0.3 version

**Comment by Vl4dimyr** [comment]
Ok, in the BepInEx console window you should see something like:

```
[Info   :   BepInEx] Loading [Shows item counts in item selection dialog (command artifact) 1.0.0]
[Info   : Unity Log] CommandItemCount loaded!
```

I will change that since it's not correct...

**Comment by charlesli524** [comment]
nope,I didn't see it, I didn't see that my Bepinex found CommandItemCount.

**Comment by Vl4dimyr** [comment]
OK do you have the latest version of BepInEx (5.3.1) and R2API (2.5.6) installed?

**Comment by charlesli524** [comment]
Oh,finally i saw the bepinex can loading it, but i still have one problem, that why i can`t command Item just like your mod screen icon when i pick up these item in the game?

**Comment by charlesli524** [comment]
R2API (2.5.6)? is it not still (2.5.0) right now?

**Comment by Vl4dimyr** [comment]
R2API is currently on 2.5.6!

Are you using the "Artifact of Command"?

**Comment by charlesli524** [comment]
So the CommandItemCount.dll need R2API (2.5.6)right now? And i did not use the "Artifact of Command",is that will effect the mod?

**Comment by Vl4dimyr** [comment]
Yes CommandItemCount needs R2API 2.5.6 (I just uploaded v1.0.4 to add dependencies, so they are shown on thunderstore)

You need to use the Artifact of Command since it lets you choose items CommandItemCount only adds the item counts to the dialog!

**Comment by charlesli524** [comment]
I just installed R2API (2.5.6) and you just updated the 1.0.4 version and then tried it again. Is CommandItemCount.dll successfully running in the game? Bepinex is successfully loading, but I have not opened Artifact. The status of the command item still does not appear, and the original item is still dropped directly

**Comment by Vl4dimyr** [comment]
If the items are dropping as usual and not as the unknown item then you are not using the Atrifact of Command in your run please take a look here https://riskofrain.fandom.com/wiki/Artifacts(RoR2) or here https://riskofrain2.gamepedia.com/Artifacts or here https://www.youtube.com/watch?v=B8yWtmXcmw0
